Repository geonetwork/geonetwork-ui, pull requests merged in 2023-09, with the labels that each got.

#612 Fix web components which rely on API version
  apps/webcomponents/src/app/webcomponents.module.ts
  libs/api/repository/src/lib/gn4/organizations/organizations-from-metadata.service.ts
Labels: bug

#622 Enlarge advanced filters behavior
  apps/datahub/src/app/home/search/search-filters/search-filters.component.ts
  libs/feature/search/src/lib/utils/service/fields.service.spec.ts
  libs/feature/search/src/lib/utils/service/fields.service.ts
  libs/feature/search/src/lib/utils/service/fields.spec.ts
  libs/feature/search/src/lib/utils/service/fields.ts
  translations/de.json
  translations/en.json
  translations/es.json
  translations/fr.json
  translations/it.json
  translations/nl.json
  translations/pt.json
Labels: enhancement, minor feature, refactoring

#516 feat: update select dropdown to match multiselect one
  apps/datafeeder/src/app/app.module.ts
  apps/datafeeder/src/app/presentation/components/data-import-validation-map-panel/data-import-validation-map-panel.component.html
  apps/datafeeder/src/index.html
  apps/datafeeder/src/styles.css
  libs/feature/dataviz/src/lib/chart-view/chart-view.component.html
  libs/feature/dataviz/src/lib/chart-view/chart-view.component.spec.ts
  libs/feature/dataviz/src/lib/chart-view/chart-view.component.stories.ts
  libs/feature/dataviz/src/lib/chart-view/chart-view.component.ts
  libs/feature/editor/src/lib/components/wizard-field/wizard-field.component.html
  libs/feature/editor/src/lib/components/wizard-field/wizard-field.component.ts
  libs/feature/record/src/lib/data-view/data-view.component.html
  libs/feature/record/src/lib/map-view/map-view.component.html
  libs/ui/catalog/src/lib/organisations-sort/organisations-sort.component.html
  libs/ui/catalog/src/lib/organisations-sort/organisations-sort.component.spec.ts
  libs/ui/inputs/src/index.ts
  libs/ui/inputs/src/lib/button/button.component.ts
  libs/ui/inputs/src/lib/dropdown-multiselect/dropdown-multiselect.component.stories.ts
  libs/ui/inputs/src/lib/dropdown-selector/dropdown-selector.component.html
  libs/ui/inputs/src/lib/dropdown-selector/dropdown-selector.component.spec.ts
  libs/ui/inputs/src/lib/dropdown-selector/dropdown-selector.component.stories.ts
  libs/ui/inputs/src/lib/dropdown-selector/dropdown-selector.component.ts
  libs/ui/inputs/src/lib/dropdown-selector/dropdown-selector.model.ts
Labels: enhancement, minor feature
