Repository geonetwork/geonetwork-ui, pull requests merged in 2023-12, with the labels that each got.

#659 Add an ElasticSearch pipeline to make formats human-readable
  docs/guide/deploy.md
  package-lock.json
  package.json
  support-services/docker-compose.yml
  tools/.gitignore
  tools/README.md
  tools/i18n/cli.js
  tools/package-lock.json
  tools/package.json
  tools/pipelines/Dockerfile
  tools/pipelines/register-es-pipelines.js
Labels: enhancement

#712 Fix gravatar service calls
  .prettierignore
  apps/metadata-editor/src/app/dashboard/search-header/search-header.component.html
  apps/metadata-editor/src/app/dashboard/search-header/search-header.component.spec.ts
  apps/metadata-editor/src/app/dashboard/search-header/search-header.component.ts
  libs/api/repository/src/lib/gn4/auth/avatar.service.interface.ts
  libs/api/repository/src/lib/gn4/auth/gravatar.service.spec.ts
  libs/api/repository/src/lib/gn4/auth/gravatar.service.ts
  libs/api/repository/src/lib/gn4/platform/gn4-platform.mapper.ts
  libs/api/repository/src/lib/gn4/platform/gn4-platform.service.spec.ts
  libs/api/repository/src/lib/gn4/platform/gn4-platform.service.ts
Labels: bug

#735 Map context: fix WMTS layer extent
  libs/feature/map/src/lib/add-layer-from-catalog/add-layer-record-preview/add-layer-record-preview.component.ts
  libs/feature/map/src/lib/map-context/map-context.model.ts
  libs/feature/map/src/lib/utils/map-utils.service.spec.ts
  libs/feature/map/src/lib/utils/map-utils.service.ts
  libs/feature/record/src/lib/map-view/map-view.component.spec.ts
  libs/feature/record/src/lib/map-view/map-view.component.ts
Labels: bug

#687 [Datahub] Add an API form generator for OGC API Records
  apps/datahub-e2e/src/e2e/datasetDetailPage.cy.ts
  apps/datahub-e2e/src/e2e/home.cy.ts
  apps/datahub/src/app/record/record-apis/record-apis.component.css
  apps/datahub/src/app/record/record-apis/record-apis.component.html
  apps/datahub/src/app/record/record-apis/record-apis.component.spec.ts
  apps/datahub/src/app/record/record-apis/record-apis.component.ts
  apps/datahub/src/app/record/record-metadata/record-metadata.component.html
  apps/datahub/src/app/record/record-metadata/record-metadata.component.spec.ts
  libs/api/metadata-converter/src/lib/common/distribution.mapper.ts
  libs/api/metadata-converter/src/lib/gn4/gn4.field.mapper.spec.ts
  libs/api/metadata-converter/src/lib/gn4/gn4.field.mapper.ts
  libs/common/domain/src/lib/model/record/metadata.model.ts
  libs/common/fixtures/src/lib/elasticsearch/metadata-links.fixtures.ts
  libs/common/fixtures/src/lib/link.fixtures.ts
  libs/ui/elements/src/lib/api-card/api-card.component.html
  libs/ui/elements/src/lib/api-card/api-card.component.spec.ts
  libs/ui/elements/src/lib/api-card/api-card.component.ts
  libs/ui/elements/src/lib/record-api-form/record-api-form.component.css
  libs/ui/elements/src/lib/record-api-form/record-api-form.component.html
  libs/ui/elements/src/lib/record-api-form/record-api-form.component.spec.ts
  libs/ui/elements/src/lib/record-api-form/record-api-form.component.ts
  libs/ui/elements/src/lib/ui-elements.module.ts
  libs/ui/inputs/src/lib/date-range-picker/date-range-picker.component.css
  libs/ui/inputs/src/lib/date-range-picker/date-range-picker.component.html
  libs/ui/inputs/src/lib/date-range-picker/date-range-picker.component.spec.ts
  libs/ui/inputs/src/lib/date-range-picker/date-range-picker.component.ts
  libs/ui/inputs/src/lib/ui-inputs.module.ts
  libs/util/shared/src/lib/links/link-classifier.service.ts
  support-services/docker-entrypoint-initdb.d/dump
  tailwind.base.css
  translations/de.json
  translations/en.json
  translations/es.json
  translations/fr.json
  translations/it.json
  translations/nl.json
  translations/pt.json
  translations/sk.json
Labels: enhancement, minor feature
