Repository geonetwork/geonetwork-ui, pull requests merged in 2023-11, with the labels that each got.

#649 Datahub / show links and APIs as a carousel
  apps/datahub-e2e/src/e2e/datasetDetailPage.cy.ts
  apps/datahub/src/app/app.module.ts
  apps/datahub/src/app/record/record-apis/record-apis.component.css
  apps/datahub/src/app/record/record-apis/record-apis.component.html
  apps/datahub/src/app/record/record-apis/record-apis.component.spec.ts
  apps/datahub/src/app/record/record-apis/record-apis.component.ts
  apps/datahub/src/app/record/record-downloads/record-downloads.component.css
  apps/datahub/src/app/record/record-downloads/record-downloads.component.html
  apps/datahub/src/app/record/record-downloads/record-downloads.component.spec.ts
  apps/datahub/src/app/record/record-downloads/record-downloads.component.ts
  apps/datahub/src/app/record/record-metadata/record-metadata.component.css
  apps/datahub/src/app/record/record-metadata/record-metadata.component.html
  apps/datahub/src/app/record/record-metadata/record-metadata.component.spec.ts
  apps/datahub/src/app/record/record-metadata/record-metadata.component.ts
  apps/datahub/src/app/record/record-otherlinks/record-otherlinks.component.css
  apps/datahub/src/app/record/record-otherlinks/record-otherlinks.component.html
  apps/datahub/src/app/record/record-otherlinks/record-otherlinks.component.spec.ts
  apps/datahub/src/app/record/record-otherlinks/record-otherlinks.component.ts
  apps/datahub/src/app/record/record-page/record-page.component.html
  apps/datahub/src/app/record/record-related-records/record-related-records.component.css
  apps/datahub/src/app/record/record-related-records/record-related-records.component.html
  apps/datahub/src/app/record/record-related-records/record-related-records.component.spec.ts
  apps/datahub/src/app/record/record-related-records/record-related-records.component.ts
  libs/feature/record/src/index.ts
  libs/feature/record/src/lib/data-apis/data-apis.component.html
  libs/feature/record/src/lib/data-apis/data-apis.component.ts
  libs/feature/record/src/lib/data-otherlinks/data-otherlinks.component.html
  libs/feature/record/src/lib/data-otherlinks/data-otherlinks.component.ts
  libs/feature/record/src/lib/feature-record.module.ts
  libs/ui/layout/src/lib/carousel/carousel.component.css
  libs/ui/layout/src/lib/carousel/carousel.component.html
  libs/ui/layout/src/lib/carousel/carousel.component.spec.ts
  libs/ui/layout/src/lib/carousel/carousel.component.stories.ts
  libs/ui/layout/src/lib/carousel/carousel.component.ts
  libs/ui/layout/src/lib/ui-layout.module.ts
  package-lock.json
  package.json
Labels: minor feature

#670 Fix [DH]: Display record's update status correctly
  libs/api/metadata-converter/src/lib/gn4/gn4.field.mapper.spec.ts
  libs/api/metadata-converter/src/lib/gn4/gn4.field.mapper.ts
  libs/api/metadata-converter/src/lib/gn4/gn4.metadata.mapper.spec.ts
Labels: bug

#663 Datahub: fine tuning
  apps/metadata-editor/src/app/app.module.ts
  conf/default.toml
  libs/ui/catalog/src/lib/organisation-preview/organisation-preview.component.html
  libs/ui/dataviz/src/lib/figure/figure.component.html
  libs/ui/dataviz/src/lib/figure/figure.component.spec.ts
  libs/ui/elements/src/lib/metadata-info/metadata-info.component.html
  libs/ui/layout/src/lib/expandable-panel/expandable-panel.component.html
  libs/ui/search/src/lib/record-preview-feed/record-preview-feed.component.html
  libs/ui/search/src/lib/record-preview-row/record-preview-row.component.html
Labels: bug

#651 Multilingual search
  conf/default.toml
  libs/api/repository/src/lib/gn4/elasticsearch/constant.ts
  libs/api/repository/src/lib/gn4/elasticsearch/elasticsearch.service.spec.ts
  libs/api/repository/src/lib/gn4/elasticsearch/elasticsearch.service.ts
Labels: minor feature

#668 DH/Bug : Links format filter filters out everything
  apps/datahub-e2e/src/e2e/datasetDetailPage.cy.ts
  libs/ui/elements/src/lib/downloads-list/downloads-list.component.spec.ts
  libs/ui/elements/src/lib/downloads-list/downloads-list.component.ts
Labels: bug

#672 Datahub: Fix abstract display in record preview
  libs/ui/search/src/lib/record-preview/record-preview.component.ts
  libs/util/shared/src/lib/utils/index.ts
  libs/util/shared/src/lib/utils/remove-whitespace.spec.ts
  libs/util/shared/src/lib/utils/remove-whitespace.ts
Labels: bug

#673 Fix [Datahub]: Do not point to future web component version
  apps/datahub/src/environments/environment.prod.ts
Labels: bug

#679 Datahub (fix): Display UpdateFrequencyCustom correctly
  libs/ui/elements/src/lib/metadata-info/metadata-info.component.html
  libs/ui/elements/src/lib/metadata-info/metadata-info.component.spec.ts
  libs/ui/elements/src/lib/metadata-info/metadata-info.component.ts
  translations/de.json
  translations/en.json
  translations/fr.json
Labels: bug, backport 2.0.x

#683 [Backport 2.0.x] Datahub (fix): Display UpdateFrequencyCustom correctly
  libs/ui/elements/src/lib/metadata-info/metadata-info.component.html
  libs/ui/elements/src/lib/metadata-info/metadata-info.component.spec.ts
  libs/ui/elements/src/lib/metadata-info/metadata-info.component.ts
  translations/de.json
  translations/en.json
  translations/fr.json
Labels: bug

#689 fix(DH): Link detection with unknown mime type
  libs/ui/elements/src/lib/downloads-list/downloads-list.component.spec.ts
  libs/util/shared/src/lib/links/link-utils.spec.ts
  libs/util/shared/src/lib/links/link-utils.ts
Labels: bug, backport 2.0.x

#690 [Backport 2.0.x] fix(DH): Link detection with unknown mime type
  libs/ui/elements/src/lib/downloads-list/downloads-list.component.spec.ts
  libs/util/shared/src/lib/links/link-utils.spec.ts
  libs/util/shared/src/lib/links/link-utils.ts
Labels: bug

#678 DH/Improve navigation button style
  libs/ui/inputs/src/lib/navigation-button/navigation-button.component.html
  tailwind.base.css
Labels: enhancement

#676 Export all libs as NPM package
  CONTRIBUTING.md
  apps/datahub/src/app/app.module.ts
  apps/map-viewer/src/app/app.module.ts
  apps/metadata-editor/src/app/app.module.ts
  apps/metadata-editor/src/app/dashboard/search-header/search-header.component.spec.ts
  apps/search/src/app/app.module.ts
  docs/.vitepress/config.ts
  docs/guide/custom-app.md
  docs/guide/theming.md
  docs/index.md
  libs/api/repository/src/index.ts
  libs/api/repository/src/lib/repository-url.ts
  libs/common/domain/src/lib/record/contact.model.ts
  libs/feature/catalog/src/index.ts
  libs/feature/dataviz/src/index.ts
  libs/feature/editor/src/index.ts
  libs/feature/map/src/index.ts
  libs/feature/map/src/lib/utils/map-utils.service.ts
  libs/feature/record/src/index.ts
  libs/feature/record/src/lib/data-view-permalink/data-view-permalink.component.spec.ts
  libs/feature/record/src/lib/data-view-permalink/data-view-permalink.component.ts
  libs/feature/record/src/lib/data-view-web-component/data-view-web-component.component.spec.ts
  libs/feature/record/src/lib/data-view-web-component/data-view-web-component.component.ts
  libs/feature/record/src/lib/feature-record.module.ts
  libs/feature/record/src/lib/gn-ui-version.token.ts
  libs/feature/router/src/lib/default/index.ts
  libs/feature/search/src/index.ts
  libs/feature/search/src/lib/facets/facets.module.ts
  libs/ui/catalog/src/index.ts
  libs/ui/dataviz/src/index.ts
  libs/ui/elements/src/index.ts
  libs/ui/inputs/src/index.ts
  libs/ui/layout/src/index.ts
  libs/ui/map/src/index.ts
  libs/ui/search/src/index.ts
  libs/ui/widgets/src/index.ts
  libs/util/shared/src/index.ts
  libs/util/shared/src/lib/pipes/index.ts
  ng-package.json
  package-lock.json
  package.json
  package/.gitignore
  package/README.md
  package/README.package.md
  package/generate-package.js
  package/index.ts
  package/ng-package.json
  package/package.json
  package/style.css
  package/tsconfig.json
  tools/file-utils.js
  tools/package.json
  tools/update-all-package-json.js
Labels: tech task

#693 Datahub (fix): Handle UpdateFrequency not defined
  libs/api/metadata-converter/src/lib/gn4/gn4.metadata.mapper.spec.ts
  libs/api/metadata-converter/src/lib/gn4/gn4.metadata.mapper.ts
  libs/ui/elements/src/lib/metadata-info/metadata-info.component.spec.ts
  libs/ui/elements/src/lib/metadata-info/metadata-info.component.ts
  libs/util/shared/src/lib/utils/remove-whitespace.spec.ts
  libs/util/shared/src/lib/utils/remove-whitespace.ts
  libs/util/shared/src/lib/utils/strip-html.spec.ts
  libs/util/shared/src/lib/utils/strip-html.ts
Labels: bug, backport 2.0.x

#701 [Backport 2.0.x] Datahub (fix): Handle UpdateFrequency not defined
  libs/api/metadata-converter/src/lib/gn4/gn4.metadata.mapper.spec.ts
  libs/api/metadata-converter/src/lib/gn4/gn4.metadata.mapper.ts
  libs/ui/elements/src/lib/metadata-info/metadata-info.component.spec.ts
  libs/ui/elements/src/lib/metadata-info/metadata-info.component.ts
  libs/util/shared/src/lib/utils/remove-whitespace.spec.ts
  libs/util/shared/src/lib/utils/remove-whitespace.ts
  libs/util/shared/src/lib/utils/strip-html.spec.ts
  libs/util/shared/src/lib/utils/strip-html.ts
Labels: bug

#705 Web component: provide gn4 platform service
  apps/webcomponents/src/app/webcomponents.module.ts
Labels: bug

#684 Datahub: Improve lineage display
  libs/ui/elements/src/lib/metadata-info/linkify.directive.spec.ts
  libs/ui/elements/src/lib/metadata-info/linkify.directive.ts
Labels: enhancement

#700 Datahub: handle filter geometry error
  libs/feature/search/src/lib/state/effects.spec.ts
  libs/feature/search/src/lib/state/effects.ts
  package-lock.json
  package.json
Labels: bug
