Repository geonetwork/geonetwork-ui, pull requests merged in 2023-07, with the labels that each got.

#513 Add ability to predefine specific search in config
  apps/datahub/src/app/app.module.ts
  apps/datahub/src/app/home/home-header/home-header.component.html
  apps/datahub/src/app/home/home-header/home-header.component.spec.ts
  apps/datahub/src/app/home/home-header/home-header.component.ts
  conf/default.toml
  libs/feature/search/src/lib/utils/service/fields.service.ts
  libs/feature/search/src/lib/utils/service/fields.spec.ts
  libs/feature/search/src/lib/utils/service/fields.ts
  libs/util/app-config/src/lib/app-config.spec.ts
  libs/util/app-config/src/lib/app-config.ts
  libs/util/app-config/src/lib/fixtures.ts
  libs/util/app-config/src/lib/model.ts
  libs/util/app-config/src/lib/parse-utils.spec.ts
  libs/util/app-config/src/lib/parse-utils.ts
  libs/util/shared/src/lib/models/search.model.ts
  libs/util/shared/src/lib/services/proxy.service.spec.ts
Labels: enhancement, major feature

#505 feat(story): add right click on news, record & org
  apps/datahub/src/app/app.module.ts
  libs/feature/catalog/src/lib/feature-catalog.module.ts
  libs/feature/catalog/src/lib/organisations/organisations.component.html
  libs/feature/catalog/src/lib/organisations/organisations.component.spec.ts
  libs/feature/catalog/src/lib/organisations/organisations.component.ts
  libs/feature/router/src/lib/default/constants.ts
  libs/feature/search/src/lib/feature-search.module.ts
  libs/feature/search/src/lib/results-list/results-list.container.component.html
  libs/feature/search/src/lib/results-list/results-list.container.component.spec.ts
  libs/feature/search/src/lib/results-list/results-list.container.component.ts
  libs/ui/catalog/src/lib/organisation-preview/organisation-preview.component.html
  libs/ui/catalog/src/lib/organisation-preview/organisation-preview.component.ts
  libs/ui/search/src/lib/record-preview-feed/record-preview-feed.component.html
  libs/ui/search/src/lib/record-preview-row/record-preview-row.component.html
  libs/ui/search/src/lib/record-preview-row/record-preview-row.component.ts
  libs/ui/search/src/lib/record-preview/record-preview.component.ts
  libs/ui/search/src/lib/results-list-item/results-list-item.component.ts
  libs/ui/search/src/lib/results-list/results-list.component.html
  libs/ui/search/src/lib/results-list/results-list.component.ts
  libs/util/shared/src/lib/services/proxy.service.spec.ts
Labels: enhancement, minor feature

#511 feat: adding organisations thumbnails to records
  libs/feature/catalog/src/lib/organisations/organisations.component.ts
  libs/feature/catalog/src/lib/organisations/service/organisations-from-groups.service.ts
  libs/feature/catalog/src/lib/organisations/service/organisations-from-metadata.service.spec.ts
  libs/feature/catalog/src/lib/organisations/service/organisations-from-metadata.service.ts
  libs/ui/search/src/lib/record-preview-row/record-preview-row.component.html
  libs/util/shared/src/lib/fixtures/groups.fixtures.ts
  libs/util/shared/src/lib/utils/atomic-operations.ts
Labels: enhancement, minor feature

#533 datahub: Favorite star bug on page change
  .prettierignore
  libs/feature/search/src/lib/favorites/favorite-star/favorite-star.component.spec.ts
  libs/feature/search/src/lib/favorites/favorite-star/favorite-star.component.ts
Labels: bug
