Repository geonetwork/geonetwork-ui, pull requests merged in 2024-09, with the labels that each got.

#985 [ME]: Create record by duplicating remote record.
  apps/metadata-editor-e2e/src/e2e/import.cy.ts
  apps/metadata-editor/src/app/records/records-list.component.ts
  apps/metadata-editor/src/app/records/search-records/search-records-list.component.html
  apps/metadata-editor/src/app/records/search-records/search-records-list.component.spec.ts
  apps/metadata-editor/src/app/records/search-records/search-records-list.component.ts
  apps/metadata-editor/src/styles.css
  libs/api/metadata-converter/src/index.ts
  libs/api/metadata-converter/src/lib/xml-utils.spec.ts
  libs/api/metadata-converter/src/lib/xml-utils.ts
  libs/api/repository/src/lib/gn4/gn4-repository.spec.ts
  libs/api/repository/src/lib/gn4/gn4-repository.ts
  libs/common/domain/src/lib/repository/records-repository.interface.ts
  libs/feature/editor/src/index.ts
  libs/feature/editor/src/lib/components/import-record/import-record.component.css
  libs/feature/editor/src/lib/components/import-record/import-record.component.html
  libs/feature/editor/src/lib/components/import-record/import-record.component.spec.ts
  libs/feature/editor/src/lib/components/import-record/import-record.component.stories.ts
  libs/feature/editor/src/lib/components/import-record/import-record.component.ts
  libs/ui/inputs/src/index.ts
  translations/de.json
  translations/en.json
  translations/es.json
  translations/fr.json
  translations/it.json
  translations/nl.json
  translations/pt.json
  translations/sk.json
Labels: minor feature

#996 Element ref wasn't working on ng-for wizard.component.html with multiple fields
  libs/feature/editor/src/lib/components/wizard/wizard.component.html
Labels: backport 2.0.x, backport 2.1.x, backport 2.3.x

#974 [ME]: Contacts for metadata
  libs/common/fixtures/src/index.ts
  libs/common/fixtures/src/lib/individual.fixtures.ts
  libs/common/fixtures/src/lib/user.fixtures.ts
  libs/feature/editor/src/lib/components/record-form/form-field/form-field-contacts/form-field-contacts.component.css
  libs/feature/editor/src/lib/components/record-form/form-field/form-field-contacts/form-field-contacts.component.html
  libs/feature/editor/src/lib/components/record-form/form-field/form-field-contacts/form-field-contacts.component.spec.ts
  libs/feature/editor/src/lib/components/record-form/form-field/form-field-contacts/form-field-contacts.component.ts
  libs/feature/editor/src/lib/components/record-form/form-field/form-field.component.html
  libs/feature/editor/src/lib/components/record-form/form-field/form-field.component.ts
  libs/feature/editor/src/lib/fields.config.ts
  translations/de.json
  translations/en.json
  translations/es.json
  translations/fr.json
  translations/it.json
  translations/nl.json
  translations/pt.json
  translations/sk.json
Labels: minor feature

#1009 [ME]: Trying to upload the same file as a resource or attachment twice fails
  libs/api/repository/src/lib/gn4/platform/gn4-platform.service.spec.ts
  libs/api/repository/src/lib/gn4/platform/gn4-platform.service.ts
  libs/common/domain/src/lib/platform.service.interface.ts
  libs/feature/editor/src/lib/components/record-form/form-field/form-field-online-link-resources/form-field-online-link-resources.component.spec.ts
  libs/feature/editor/src/lib/components/record-form/form-field/form-field-online-link-resources/form-field-online-link-resources.component.ts
  libs/feature/editor/src/lib/components/record-form/form-field/form-field-online-resources/form-field-online-resources.component.ts
  libs/feature/editor/src/lib/components/record-form/form-field/form-field-overviews/form-field-overviews.component.spec.ts
  libs/feature/editor/src/lib/components/record-form/form-field/form-field-overviews/form-field-overviews.component.ts
  libs/util/shared/src/lib/utils/index.ts
  libs/util/shared/src/lib/utils/no-duplicate-file-name.spec.ts
  libs/util/shared/src/lib/utils/no-duplicate-file-name.ts
Labels: bug fix

#1010 [ME]: Error when trying to import a record from Geocat.ch
  apps/metadata-editor/src/app/dashboard/dashboard-menu/dashboard-menu.component.spec.ts
  apps/metadata-editor/src/app/dashboard/dashboard-menu/dashboard-menu.component.ts
  libs/api/metadata-converter/src/lib/iso19115-3/write-parts.spec.ts
  libs/api/metadata-converter/src/lib/iso19115-3/write-parts.ts
  libs/api/metadata-converter/src/lib/iso19139/write-parts.spec.ts
  libs/api/metadata-converter/src/lib/iso19139/write-parts.ts
  libs/api/metadata-converter/src/lib/xml-utils.spec.ts
  libs/api/metadata-converter/src/lib/xml-utils.ts
  libs/api/repository/src/lib/gn4/gn4-repository.spec.ts
  libs/api/repository/src/lib/gn4/gn4-repository.ts
  libs/common/domain/src/lib/repository/records-repository.interface.ts
Labels: bug fix
